<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Rebus.RabbitMq" Version="10.1.1" />
      <PackageReference Include="Rebus.ServiceProvider" Version="10.7.2" />
      <PackageReference Include="Trellis.Asp" Version="3.0.0-alpha.158" />
    </ItemGroup>

</Project>
